version: '3.8'

services:
  backend:
    build:
      context: ./swift_demo       
      dockerfile: Dockerfile       
    ports:
      - "8080:8080"                
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/swift_demo
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres

    depends_on:
      - db
    networks:
      - swift_demo-network

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: swift_demo      
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"               
    volumes:
      - db-data:/var/lib/postgresql/data
    networks:
      - swift_demo-network

volumes:
  db-data:

networks:
  swift_demo-network:
    driver: bridge
